FROM maven:3.9.6-eclipse-temurin-17-alpine AS thick

WORKDIR /app
COPY . .
RUN mvn clean install

FROM eclipse-temurin:17 AS thin
WORKDIR /app

ARG GOOGLE_CLOUD_FIREWALL_NAME
ARG GOOGLE_CLOUD_PROJECT
ARG GOOGLE_CLOUD_VM_NAME
ARG GOOGLE_CLOUD_VM_ZONE
ARG MINECRAFT_SERVER_PORT

# new
ARG FE_HOST
ARG SIGNING_SECRET
ARG GITHUB_CLIENT_ID
ARG GITHUB_CLIENT_SECRET
ARG GOOGLE_CLOUD_BUCKET_NAME

ARG MINECRAFT_RCON_PORT
ARG MINECRAFT_RCON_PASS

COPY --from=thick /app/infra/starter.sh .
COPY --from=thick /app/target/validator-0.0.1-SNAPSHOT.jar .

ENV GOOGLE_CLOUD_FIREWALL_NAME=$GOOGLE_CLOUD_FIREWALL_NAME
ENV GOOGLE_CLOUD_PROJECT=$GOOGLE_CLOUD_PROJECT
ENV GOOGLE_CLOUD_VM_NAME=$GOOGLE_CLOUD_VM_NAME
ENV GOOGLE_CLOUD_VM_ZONE=$GOOGLE_CLOUD_VM_ZONE
ENV MINECRAFT_SERVER_PORT=$MINECRAFT_SERVER_PORT

# new
ENV FE_HOST=$FE_HOST
ENV SIGNING_SECRET=$SIGNING_SECRET
ENV GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID
ENV GITHUB_CLIENT_SECRET=$GITHUB_CLIENT_SECRET
ENV GOOGLE_CLOUD_BUCKET_NAME=$GOOGLE_CLOUD_BUCKET_NAME

ENV MINECRAFT_RCON_PORT=$MINECRAFT_RCON_PORT
ENV MINECRAFT_RCON_PASS=$MINECRAFT_RCON_PASS

RUN chmod 755 starter.sh
CMD ["bash", "./starter.sh"]