ARG GOOGLE_CLOUD_FIREWALL_NAME
ARG GOOGLE_CLOUD_PROJECT
ARG GOOGLE_CLOUD_VM_NAME
ARG GOOGLE_CLOUD_VM_ZONE
ARG MINECRAFT_SERVER_PORT

FROM maven:3.9.6-eclipse-temurin-17-alpine AS thick

WORKDIR /app
COPY . .
RUN mvn clean install

FROM eclipse-temurin:17 AS thin

WORKDIR /app
COPY --from=thick /app/infra/starter.sh .
COPY --from=thick /app/target/validator-0.0.1-SNAPSHOT.jar .

ENV GOOGLE_CLOUD_FIREWALL_NAME=$GOOGLE_CLOUD_FIREWALL_NAME
ENV GOOGLE_CLOUD_PROJECT=$GOOGLE_CLOUD_PROJECT
ENV GOOGLE_CLOUD_VM_NAME=$GOOGLE_CLOUD_VM_NAME
ENV GOOGLE_CLOUD_VM_ZONE=$GOOGLE_CLOUD_VM_ZONE
ENV MINECRAFT_SERVER_PORT=$MINECRAFT_SERVER_PORT

RUN chmod 755 starter.sh
CMD bash -c "./starter.sh"