#!/bin/bash

java -Xmx768m \
    -DGOOGLE_CLOUD_PROJECT="${GOOGLE_CLOUD_PROJECT}" \
    -DGOOGLE_CLOUD_VM_ZONE="${GOOGLE_CLOUD_VM_ZONE}" \
    -DGOOGLE_CLOUD_VM_NAME="${GOOGLE_CLOUD_VM_NAME}" \
    -DGOOGLE_CLOUD_FIREWALL_NAME="${GOOGLE_CLOUD_FIREWALL_NAME}" \
    -DGOOGLE_CLOUD_BUCKET_NAME="${GOOGLE_CLOUD_BUCKET_NAME}" \
    -DMINECRAFT_SERVER_PORT="${MINECRAFT_SERVER_PORT}" \
    -DMINECRAFT_RCON_PORT="${MINECRAFT_RCON_PORT}" \
    -DMINECRAFT_RCON_PASS="${MINECRAFT_RCON_PASS}" \
    -DFE_HOST="${FE_HOST}" \
    -DSIGNING_SECRET="${SIGNING_SECRET}" \
    -DGITHUB_CLIENT_ID="${GITHUB_CLIENT_ID}" \
    -DGITHUB_CLIENT_SECRET="${GITHUB_CLIENT_SECRET}" \
    -jar validator-0.0.1-SNAPSHOT.jar