#!/bin/bash

java -Xmx768m \
    -DGOOGLE_CLOUD_PROJECT="${GOOGLE_CLOUD_PROJECT}" \
    -DGOOGLE_CLOUD_VM_ZONE="${GOOGLE_CLOUD_VM_ZONE}" \
    -DGOOGLE_CLOUD_VM_NAME="${GOOGLE_CLOUD_VM_NAME}" \
    -DGOOGLE_CLOUD_FIREWALL_NAME="${GOOGLE_CLOUD_FIREWALL_NAME}" \
    -DMINECRAFT_SERVER_PORT="${MINECRAFT_SERVER_PORT}" \
    -jar validator-0.0.1-SNAPSHOT.jar