spring:
  banner:
    location: classpath:/ban.txt
  application:
    name: validator

auth:
  security:
    white-list-urls:
      /api/v2/auth/**,
      /api/v2/ping,
      /api/v2/machine,
      /api/v2/firewall,
      /api/v2/firewall/add-ip,
      /api/v2/firewall/check-ip,
      /api/v2/server-info,
      /misc/**

springdoc: # http://localhost:8080/misc/swagger-ui/index.html
  api-docs:
    path: /misc/api-docs
  swagger-ui:
    path: /misc/swagger-ui.html
    enabled: true
    tagsSorter: alpha
    operationsSorter: method

google:
  project-id: ${GOOGLE_CLOUD_PROJECT}
  compute:
    zone: ${GOOGLE_CLOUD_VM_ZONE}
    instance-name: ${GOOGLE_CLOUD_VM_NAME}
    firewall-name: ${GOOGLE_CLOUD_FIREWALL_NAME}

minecraft-server:
  port: {MINECRAFT_SERVER_PORT}

github:
  client_id: ${GITHUB_CLIENT_ID}
  client_secret: ${GITHUB_CLIENT_SECRET}
  redirect_uri: ${GITHUB_CLIENT_REDIRECT_URI}
  authorized-email: ${GITHUB_AUTH_EMAIL}

logging:
    com:
      arhum:
        validator: DEBUG
